version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: mvc_nginx
    ports:
      - 80:80
    volumes:
      - ./conf/default-front.conf:/etc/nginx/conf.d/default.conf
      - ./front:/var/www/html
    depends_on:
      - php
    networks:
      - app-network

  mysql:
    image: mysql:latest
    container_name: mvc_mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    command: "mysqld --init-file /data/application/init.sql"
    volumes:
      - ./conf/website.sql:/data/application/init.sql
      - db_data:/var/lib/mysql
    networks:
      - app-network

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: mvc_myadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - ${IP}:8080:80
    networks:
      - app-network

  php:
    build: ./conf
    container_name: mvc_php
    ports:
      - 9000:9000
    volumes:
      - ./front:/var/www/html
      - ./conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_HOST: mysql
      MYSQL_DB: ${DB_NAME}
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge